# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hera < Formula
  desc ""
  homepage "https://github.com/nuntiodev/cli"
  version "0.0.29"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nuntiodev/cli/releases/download/v0.0.29/cli_Darwin_x86_64.tar.gz"
      sha256 "e2b21123681aba4154f62efcc567a5e17ca0e100ffbb5423ccb798b964a6515b"

      def install
        bin.install "cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nuntiodev/cli/releases/download/v0.0.29/cli_Darwin_arm64.tar.gz"
      sha256 "19113882d524b4f2c8829fd0a158fc9a25d19a718ad449dcdb2573ed11d3af43"

      def install
        bin.install "cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nuntiodev/cli/releases/download/v0.0.29/cli_Linux_arm64.tar.gz"
      sha256 "4ee7fe68a26a73fb49a59b3c9ac78d6042e749086d9da54522f37b5082e1b93a"

      def install
        bin.install "cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/nuntiodev/cli/releases/download/v0.0.29/cli_Linux_x86_64.tar.gz"
      sha256 "4ad4750b7cb5dfcd38d8eabe9c5a86a6c3a62d45361e85c3d907d131d50c686c"

      def install
        bin.install "cli"
      end
    end
  end
end
