# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nuntio < Formula
  desc ""
  homepage "https://github.com/nuntiodev/cli/nuntio"
  version "0.0.49"

  on_macos do
    url "https://github.com/nuntiodev/cli/releases/download/v0.0.49/cli_0.0.49_darwin_all.tar.gz"
    sha256 "cea4eb7dfc600d08db1e97416d7826e9d7b91d7161a3e62dea165ea174af1dbc"

    def install
      bin.install "cli"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nuntiodev/cli/releases/download/v0.0.49/cli_0.0.49_linux_arm64.tar.gz"
      sha256 "646087ca89cd75cdbdd4437de8d9154b4fa3ec3bd00d92432866e2cf5aa4bd6e"

      def install
        bin.install "cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/nuntiodev/cli/releases/download/v0.0.49/cli_0.0.49_linux_amd64.tar.gz"
      sha256 "0dfcec78030424b22af80c9eb37080bc2bcdfe840c2260f455402ae5b664e45a"

      def install
        bin.install "cli"
      end
    end
  end
end
