# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NuntioAdmin < Formula
  desc ""
  homepage ""
  version "0.1.0-rc.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nuntiodev/nuntio/releases/download/v0.1.0-rc.3/nuntio-server_darwin_x86_64.tar.gz"
      sha256 "cb9811b39244f21b3dfe1e63d76289e1317c992031435ca5627bca9e289ea4dc"

      def install
        bin.install "nuntio-admin"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nuntiodev/nuntio/releases/download/v0.1.0-rc.3/nuntio-server_darwin_arm64.tar.gz"
      sha256 "bc97afd57854fe8e90820960c181e170fed0f5197d17d78614dde5d84047350d"

      def install
        bin.install "nuntio-admin"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nuntiodev/nuntio/releases/download/v0.1.0-rc.3/nuntio-server_linux_arm64.tar.gz"
      sha256 "faf6a07c63841f282955e9c051a00c94ddb86a4e63151a2b02f17d05b24b2fc4"

      def install
        bin.install "nuntio-admin"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/nuntiodev/nuntio/releases/download/v0.1.0-rc.3/nuntio-server_linux_x86_64.tar.gz"
      sha256 "8c5e26ed2ae779a94d1fd8c5a8615095b91d092309168897ad34e64522b2d0bc"

      def install
        bin.install "nuntio-admin"
      end
    end
  end
end
